"""Domain vocabulary every Sincpro service shares, with no infrastructure behind it.

`ValueObject` builds a validated primitive. `Entity` is what an aggregate carries and how it
names itself for a screen. `Criteria` says what to read, `EntityCollection` what came back, `Meta`
what a model publishes about itself, `IRepository` the least a store answers, and
`DomainEvent` what happened.

Nothing here imports an ORM. Running a criteria against a database is `sincpro_framework.orm`,
an optional extra; carrying events is `sincpro_framework.event_driven`.
"""

from sincpro_framework.ddd.criteria import (
    TEXT,
    All,
    Any,
    Bucket,
    Condition,
    CountMode,
    Criteria,
    Cursor,
    Not,
    Offset,
    Operator,
    Pagination,
    Pivot,
    PivotCell,
    Sort,
    Specification,
    holds,
    matches,
)
from sincpro_framework.ddd.drafts import (
    Draft,
    DraftConflict,
    Drafts,
    InMemoryDrafts,
    KeyValueDrafts,
    refuse_stale,
)
from sincpro_framework.ddd.entity import (
    ArchivableMixin,
    AuditedMixin,
    ChangeTrackingMixin,
    Entity,
    EntityUpdated,
    EventSourcedMixin,
    Translated,
    new_entity_id,
    utc_now,
)
from sincpro_framework.ddd.entity.derivations import Derivations, Derive
from sincpro_framework.ddd.entity.editing import assign, recompute, recompute_whole
from sincpro_framework.ddd.entity.entity_collection import (
    Changes,
    Count,
    Dropped,
    EntityCollection,
)
from sincpro_framework.ddd.entity.model_meta import (
    FieldMeta,
    FieldType,
    Meta,
    presentation_of,
)
from sincpro_framework.ddd.entity.presentation import (
    AllHold,
    AnyHolds,
    Is,
    Presentation,
    When,
)
from sincpro_framework.ddd.entity.query_entity import NAME_SEARCH_LIMIT, detail_of, matching
from sincpro_framework.ddd.entity.relations import BusResolver, Relation, Resolver
from sincpro_framework.ddd.events import (
    DeliverableEventMixin,
    DomainEvent,
)
from sincpro_framework.ddd.exceptions import (
    AggregateNotFound,
    ConstraintViolation,
    ContractViolation,
    DomainError,
    DuplicateAggregate,
    InvalidCriteria,
    RelationNotResolved,
    StaleAggregate,
    TimedOut,
    TransactionConflict,
    WriteInPreview,
)
from sincpro_framework.ddd.preview import Advice, advise, is_previewing, previewing
from sincpro_framework.ddd.query import (
    Query,
    ResponsePaginatedQuery,
    ResponseRecord,
    ResponseRecords,
)
from sincpro_framework.ddd.reads import (
    EntityReads,
    FieldState,
    Get,
    GetMany,
    LiteralSearch,
    Preview,
    ResponsePreview,
    Search,
)
from sincpro_framework.ddd.repositories import (
    AggregateRepository,
    Analyzes,
    ChangeTrackingRepositoryMixin,
    INumbering,
    IRepository,
    MemoryNumbering,
    MemoryRepository,
    ReadsAggregates,
    StoreCapabilities,
    Transacts,
    Upserted,
    WritesAggregates,
    WritesInBulk,
)
from sincpro_framework.ddd.repositories.hooks import Hook, Hooks
from sincpro_framework.ddd.value_object import ValueObject

__all__ = [
    "Draft",
    "DraftConflict",
    "Drafts",
    "InMemoryDrafts",
    "KeyValueDrafts",
    "refuse_stale",
    "NAME_SEARCH_LIMIT",
    "AllHold",
    "AnyHolds",
    "Is",
    "When",
    "presentation_of",
    "Presentation",
    "detail_of",
    "matching",
    "AggregateRepository",
    "Analyzes",
    "MemoryNumbering",
    "INumbering",
    "ReadsAggregates",
    "StoreCapabilities",
    "Transacts",
    "WritesAggregates",
    "WritesInBulk",
    "All",
    "Any",
    "ArchivableMixin",
    "AuditedMixin",
    "Bucket",
    "BusResolver",
    "EntityCollection",
    "ChangeTrackingMixin",
    "EventSourcedMixin",
    "Condition",
    "Changes",
    "Count",
    "CountMode",
    "Criteria",
    "Cursor",
    "DomainEvent",
    "Dropped",
    "DuplicateAggregate",
    "ConstraintViolation",
    "TransactionConflict",
    "TimedOut",
    "AggregateNotFound",
    "EntityReads",
    "Get",
    "LiteralSearch",
    "ResponseRecord",
    "ResponseRecords",
    "GetMany",
    "Search",
    "Advice",
    "Derivations",
    "Derive",
    "FieldState",
    "Preview",
    "ResponsePreview",
    "WriteInPreview",
    "advise",
    "assign",
    "previewing",
    "is_previewing",
    "recompute",
    "recompute_whole",
    "Entity",
    "EntityUpdated",
    "ChangeTrackingRepositoryMixin",
    "Hook",
    "Hooks",
    "DeliverableEventMixin",
    "FieldMeta",
    "FieldType",
    "InvalidCriteria",
    "MemoryRepository",
    "Meta",
    "Not",
    "Offset",
    "Operator",
    "DomainError",
    "ContractViolation",
    "Pagination",
    "Pivot",
    "PivotCell",
    "Query",
    "Relation",
    "IRepository",
    "Upserted",
    "Resolver",
    "ResponsePaginatedQuery",
    "Sort",
    "Specification",
    "TEXT",
    "RelationNotResolved",
    "StaleAggregate",
    "Translated",
    "ValueObject",
    "holds",
    "matches",
    "new_entity_id",
    "utc_now",
]
