name: "Prepare envinronment"
description: "Install OS packages and dependencies"

inputs:
  enviroment:
    description: "Python versions to setup"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.enviroment }}
