"""`AlembicEngine`: a SQL store migrated by Alembic — the engine the framework ships.

    billing_migrations.store("main", AlembicEngine(tables.metadata, database))

Context: one linear chain and one version table per (context × store) —
`alembic_version__<context>__<store>` — never Alembic branches, whose downgrades across bases
corrupt the version table. The step id is the Alembic revision id, the body is autogenerated
from the context's own `MetaData`, and the environment is the framework's: there is no
`alembic.ini` to keep in step with the code. On a database whose DDL is not transactional —
SQLite, MySQL — a step that fails part-way is recorded dirty in `<version table>_dirty`.

A step body imports only `sqlalchemy` and `alembic`: a column type the project declares — a
`TypeDecorator` such as `JsonText` — is written as the type it stores, its `impl`, so a body
never imports project code and never calls a constructor whose arguments `repr()` does not
show. `render_types` writes a type some other way.
"""

import re
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Literal, cast

from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.autogenerate.api import AutogenContext
from alembic.autogenerate.render import _repr_type
from alembic.config import Config
from alembic.ddl.impl import DefaultImpl
from alembic.runtime.environment import (
    IncludeNameFn,
    NameFilterParentNames,
    NameFilterType,
    RenderItemFn,
)
from alembic.runtime.migration import MigrationContext
from alembic.script import Script
from alembic.util import CommandError
from sqlalchemy import (
    Column,
    Connection,
    MetaData,
    String,
    Table,
    TypeDecorator,
    delete,
    insert,
    inspect,
    select,
)
from sqlalchemy.types import TypeEngine

from sincpro_framework.migrations.domain import (
    Chain,
    MigrationEngine,
    MigrationRefused,
    Position,
    Step,
)
from sincpro_framework.orm.sqlalchemy.database import Database

RenderTypes = Mapping[type[TypeEngine[Any]], TypeEngine[Any]]
"""A column type class — or a base of it — and the SQLAlchemy type a step writes for it."""

ENVIRONMENT = Path(__file__).parent / "environment"
LONGEST_NAME = 63
"""Postgres truncates longer identifiers silently — two chains could end on one version table."""


def version_table(chain: Chain) -> str:
    name = re.sub(
        r"[^a-z0-9_]", "_", f"alembic_version__{chain.context}__{chain.store}".lower()
    )
    if len(name) + len("_dirty") > LONGEST_NAME:
        raise ValueError(
            f"{chain.key} makes the version table {name}, longer than {LONGEST_NAME} characters "
            "with its _dirty table — shorten the context or store name"
        )
    return name


def only_tables_of(metadata: MetaData) -> IncludeNameFn:
    """Autogenerate and drift look only at the context's own tables — the other contexts' tables
    and version tables on the same database are someone else's."""

    def include_name(
        name: str | None, type_: NameFilterType, parent_names: NameFilterParentNames
    ) -> bool:
        if type_ != "table":
            return True
        schema = parent_names.get("schema_name")
        return (f"{schema}.{name}" if schema else name) in metadata.tables

    return include_name


def _written_as(type_: TypeEngine[Any], render_types: RenderTypes) -> TypeEngine[Any] | None:
    """The type a step writes in place of `type_`; `None` for Alembic's own rendering.

    Context: a type SQLAlchemy ships stays itself — `Interval` is a `TypeDecorator` too, and a
    native one on Postgres."""
    for cls in type(type_).__mro__:
        if cls in render_types:
            return render_types[cls]
    shipped = type(type_).__module__.startswith("sqlalchemy.")
    if isinstance(type_, TypeDecorator) and not shipped:
        return type_.impl_instance
    return None


def rendering_types(render_types: RenderTypes) -> RenderItemFn:
    """How autogenerate writes a column type in a step body.

    Context: the chosen type goes back through Alembic's own `_repr_type`, so its `sa.` prefix,
    its dialect imports and a decorator nested in another are written as Alembic writes any
    type."""

    def render_item(
        type_: str, obj: Any, autogen_context: AutogenContext
    ) -> str | Literal[False]:
        written = _written_as(obj, render_types) if type_ == "type" else None
        return False if written is None else _repr_type(written, autogen_context)

    return render_item


def _describe(difference: tuple) -> str:
    """One Alembic difference as a sentence."""
    kind = difference[0]
    if kind == "add_table":
        return f"table {difference[1].name} is declared but no step creates it"
    if kind == "remove_table":
        return f"table {difference[1].name} is in the store but not declared"
    if kind == "add_column":
        return f"column {difference[2]}.{difference[3].name} is declared but no step adds it"
    if kind == "remove_column":
        return f"column {difference[2]}.{difference[3].name} is in the store but not declared"
    if kind in ("add_index", "remove_index"):
        where = "declared but no step creates it" if kind == "add_index" else "not declared"
        return f"index {difference[1].name} is {where}"
    return str(difference)


def _dirty_table(chain: Chain) -> Table:
    return Table(f"{version_table(chain)}_dirty", MetaData(), Column("head", String(64)))


class AlembicEngine(MigrationEngine):
    """The chain of one context's `MetaData` on one `Database`.

    `render_types` maps a column type class — or a base of it — to the SQLAlchemy type a step
    writes for it: for a type with no `impl` (a `UserDefinedType`), or a `TypeDecorator` whose
    database type is not its `impl` (one that overrides `load_dialect_impl`).

        AlembicEngine(tables.metadata, database, render_types={Vector: sa.Text()})

    Context: a mapping of types, not a hook over Alembic's rendering — a type is the one thing
    a project declares that the framework cannot write for it, and a SQLAlchemy type instance
    is written by Alembic itself, imports included. What it maps to must be what the column is
    in the database, or `check` reports the difference.
    """

    name = "alembic"

    def __init__(
        self, metadata: MetaData, database: Database, render_types: RenderTypes | None = None
    ) -> None:
        self.metadata = metadata
        self.database = database
        self.render_types: RenderTypes = dict(render_types or {})
        dialect = database.engine.dialect
        self.transactional = DefaultImpl.get_by_dialect(dialect).transactional_ddl

    def _config(self, chain: Chain, connection: Connection) -> Config:
        config = Config()
        config.set_main_option("script_location", str(ENVIRONMENT))
        config.set_main_option("version_locations", str(chain.folder))
        config.set_main_option("path_separator", "os")
        config.attributes["connection"] = connection
        config.attributes["metadata"] = self.metadata
        config.attributes["version_table"] = version_table(chain)
        config.attributes["render_item"] = rendering_types(self.render_types)
        return config

    def position(self, chain: Chain) -> Position:
        dirty = _dirty_table(chain)
        with self.database.engine.connect() as connection:
            migration = MigrationContext.configure(
                connection, opts={"version_table": version_table(chain)}
            )
            heads = migration.get_current_heads()
            is_dirty = inspect(connection).has_table(dirty.name) and (
                connection.execute(select(dirty.c.head)).first() is not None
            )
        if len(heads) > 1:
            raise MigrationRefused(
                f"{chain.key} has several heads in {version_table(chain)}: {', '.join(heads)} — "
                "look at the store, then resolve it at the one it stands on"
            )
        return Position(heads[0] if heads else None, is_dirty)

    def record(self, chain: Chain, position: Position) -> None:
        dirty = _dirty_table(chain)
        with self.database.engine.begin() as connection:
            command.stamp(
                self._config(chain, connection), position.head or "base", purge=True
            )
            if position.dirty:
                dirty.create(connection, checkfirst=True)
            if inspect(connection).has_table(dirty.name):
                connection.execute(delete(dirty))
                if position.dirty:
                    connection.execute(insert(dirty).values(head=position.head))

    def apply(self, chain: Chain, step: Step) -> None:
        with self.database.engine.begin() as connection:
            command.upgrade(self._config(chain, connection), step.id)

    def revert(self, chain: Chain, step: Step) -> None:
        with self.database.engine.begin() as connection:
            command.downgrade(self._config(chain, connection), step.parent or "base")

    def scaffold(self, chain: Chain, step: Step) -> Path:
        """Autogenerated from the context's tables against the store as it stands — which must be
        on the chain's last step, as for any autogenerate."""
        chain.folder.mkdir(parents=True, exist_ok=True)
        try:
            with self.database.engine.begin() as connection:
                script = command.revision(
                    self._config(chain, connection),
                    message=step.message,
                    autogenerate=True,
                    rev_id=step.id,
                    head=step.parent or "base",
                    version_path=str(chain.folder),
                )
        except CommandError as error:
            raise MigrationRefused(
                f"{chain.key}: {error} — upgrade it before writing a new step"
            ) from error
        return Path(cast(Script, script).path)

    def drift(self, chain: Chain) -> list[str] | None:
        with self.database.engine.connect() as connection:
            migration = MigrationContext.configure(
                connection,
                opts={
                    "version_table": version_table(chain),
                    "include_name": only_tables_of(self.metadata),
                },
            )
            differences = compare_metadata(migration, self.metadata)
        return [_describe(one) for one in differences]
