name: Check code style

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - main

jobs:
  checks:
    name: Run formatting & lint checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install pipx
        run: |
          python -m pip install --upgrade pip pipx

      - name: Expose pipx binaries
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install Python tools via pipx
        run: make init

      - name: Verify code format
        run: make verify-format
