name: Check code

# Run this workflow every time a new commit pushed to your repository
on: push

env:
  GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}

jobs:
  validate:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.12, 3.13]
    uses: Sincpro-SRL/.github/.github/workflows/02-check-code.yaml@main
    secrets: inherit
