name: Run tests

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  run_tests:
    name: Run test

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python version ${{ matrix.python-version }} to test
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: run tests
        run: make test
