name: Release Drafter PR Auto Labels

on:
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [ opened, reopened, synchronize ]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next release notes as pull requests that are merged into "main"
      - uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
